        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 25 10:21:44 2018
        MODULE PART_BENDING_HOR__genmod
          INTERFACE 
            SUBROUTINE PART_BENDING_HOR(IPS,VAL_BEND,TOUT)
              INTEGER(KIND=4) :: IPS
              REAL(KIND=4) :: VAL_BEND
              REAL(KIND=4) :: TOUT
            END SUBROUTINE PART_BENDING_HOR
          END INTERFACE 
        END MODULE PART_BENDING_HOR__genmod
