        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 25 10:21:42 2018
        MODULE PART_BENDING_Z__genmod
          INTERFACE 
            SUBROUTINE PART_BENDING_Z(IPS,VAL_BEND,TOUT)
              INTEGER(KIND=4) :: IPS
              REAL(KIND=4) :: VAL_BEND
              REAL(KIND=4) :: TOUT
            END SUBROUTINE PART_BENDING_Z
          END INTERFACE 
        END MODULE PART_BENDING_Z__genmod
